- .travis.yml
> fix CI for bors

- examples/bench.rs
> improve the benchmark

- src/imp_pl.rs
- src/imp_std.rs
> Make get_or_init faster with some unsafe

- CHANGELOG.md
- Cargo.toml
- src/imp_pl.rs
- src/imp_std.rs
- src/lib.rs
- tests/test.rs
> implement get_or_try_init for sync::OnceCell

- src/imp_pl.rs
- src/imp_std.rs
- src/lib.rs
- tests/test.rs
> Added OnceCell::into_inner() for sync and unsync.

- CHANGELOG.md
- Cargo.toml
> publish v0.2.2

- src/lib.rs
- tests/test.rs
> Implemented Clone for sync::OnceCell.

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
> updated `Deref` impls to use `FnOnce`

- src/imp_pl.rs
- src/imp_std.rs
- src/lib.rs
> lift common code from impls

- src/imp_std.rs
> add comment about MaybeUninit

- README.md
- src/lib.rs
> clarify API

- Cargo.toml
- examples/bench_vs_lazy_static.rs
> benchmark vs lazy_static

- CHANGELOG.md
- src/lib.rs
- tests/test.rs
closes #46
r? @xfix 
cc @KrishnaSannasi
> Sound lazy

- .travis.yml
> schedule miri tests to run first on CI

- Cargo.toml
> require std feature for lazy_static benchmark

- src/lib.rs
> explain that reentrancy is tricky

- src/imp_pl.rs
- src/imp_std.rs
> actually run size tests

- .travis.yml
> actually test parking_lot on CI

- examples/reentrant_init_deadlocks.rs
> Paper over unfortunate --all-targets interaction

- src/imp_std.rs
> Incorporate latest changes from std

- src/lib.rs
> Document synchronization effects of OnceCell

- CHANGELOG.md
- Cargo.toml
- README.md
> Release 1.3.0

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
> Don't require Debug bound closure for Lazy

- CHANGELOG.md
- src/lib.rs
> Compat with 1.31.1

- src/imp_std.rs
> Remove fixme

- src/lib.rs
> Document lateinit pattern

- src/lib.rs
- xtask/src/main.rs
> :arrow_up: MSRV

- src/lib.rs
> Switch doc style

- src/race.rs
> Minimize unsafe scope

- CHANGELOG.md
- Cargo.toml
- src/race.rs
- tests/it.rs
> publish v1.5.2

- Cargo.toml
- src/imp_std.rs
- src/lib.rs
> Clarify docs regarding parking_lot

- CHANGELOG.md
- Cargo.toml
- tests/it.rs
> Release 1.7.0

- CHANGELOG.md
- Cargo.toml
- src/imp_pl.rs
- src/imp_std.rs
- src/lib.rs
> publish 1.7.2

- src/lib.rs
> Add TestResource recipe

- src/lib.rs
> Call attention to a footgun

- src/lib.rs
> Cleanup docs

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/race.rs
> Add try insert

- Cargo.toml
> stabilize try_insert method

- src/imp_std.rs
- tests/it.rs
Barriers, concurrency, and spinloops should all work now.
> Miri has gained some more features

- CHANGELOG.md
- Cargo.toml
- src/imp_std.rs
> simplify strict-provenance polyfill

- .github/workflows/ci.yaml
> fix token name

- Cargo.toml
> release 1.15.0

- CHANGELOG.md
- Cargo.toml
> publish 1.16.0

- CHANGELOG.md
- Cargo.toml
Adds changelog entry for #219
Extracted from #221 since that needs [a higher MSRV ](https://github.com/rust-lang/rust/pull/98383).
> Bump version to 1.17.1 and update the changelog.

- CHANGELOG.md
- Cargo.lock.msrv
- Cargo.toml
> release 1.18.0

- src/race.rs
Do what the TODO says.
The awkward construct is to avoid an `as *const T` cast.
> Use `<*const T>::cast_mut()` now that we have MSRV 1.65.
