matklad/once_cell

- src/imp_pl.rs
- src/imp_std.rs
- src/lib.rs
- tests/test.rs
I'd like to use this within System76 / Pop!_OS projects, but that requires an extra derive (PartialEq), and using `use` import syntax that's compatible with rustc 1.24.1. While I was there, added some additional missing derives (Hash, From<T>).
> Add PartialEq, From<T> derives + Fix rustc 1.24.1 builds

- Cargo.lock.min
- Cargo.toml
- tests/test.rs
I'm currently attempting to package this crate for [Fedora](https://fedoraproject.org) which already contains version `0.6.3` of the `crossbeam-utils` crate; in order to do so, the dependencies have to be updated to use compatible version.
The changes needed are fairly small (AFAIK only function signature changes and only in test suite), so I went ahead and prepared a patch.
Let me know if there is anything else I can do to help.
> Update crossbeam-utils to ^0.6.0

- src/lib.rs
They're not required anymore so I removed them
Thanks for the neat crate
> remove macro_use in code and comments

- README.md
- src/lib.rs
cc @BurntSushi
I think I can do a neat trick of guaranteeing conservative MSRV if features are disabled. 
With `parking_lot` feature enabled, I am bound to at least that crate's MSRV, so I can't make promises.
Additionally, at some point, when `std::sync::Mutex::new` becomes `const`, I'd like to take advantage of that. I plan to add a *default* `std_once_cell_get_or_try_init` feature at that moment, which will bump MSRV *if* you use default features. 
Also, the crate's version is currently 0.2, but, API-wise, I am ready to do 1.0. However I'd prefer to do that later (months?) lest someone finds a critical issue with the current interface.
> Specify MSRV policy

- src/lib.rs
As per https://github.com/matklad/once_cell/issues/1, I have looked at `unsync::OnceCell` code, and found that `::once_cell::unsync::OnceCell::set` is unsound when combined with `::once_cell::unsync::OnceCell::get`:
- for a brief moment, before `Err`-oring, we have a unique reference to the inner `Option<T>`, despite it being potentially aliased by a previous `.get()` borrow.
For instance, miri rejects the following code:
```rust
fn main ()
{
let x = ::once_cell::unsync::OnceCell::new();
x.set(42).unwrap();
let at_x = x.get().unwrap(); // --- (shared) borrow of inner `Option<T>` --+
let _ = x.set(27); // <-- temporary (unique) borrow of inner `Option<T>`   |
println!("{}", at_x); // <------- up until here ---------------------------+
}
```
Changing the kind of borrow with which the …
> Fix unsync unsound aliasing of Option<T>

- src/lib.rs
- tests/test.rs
This avoids unnecessarily verbose debug formatting like OnceCell(OnceCell(Some(XXX))).
This also prevents implementation details from leaking out to debug messages
printed by clients of once_cell crate.
> Feature: Less verbose implementation of fmt::Debug for sync::OnceCell and unsync::OnceCell.

- src/lib.rs
- tests/test.rs
This change allows for more ergonomic usage of `Lazy` when embedded in other types or on the stack (not a global `static`). It does this by allowing strictly more types of closures to be used with `Lazy`.
> changed `Lazy` to use `FnOnce` instead of `Fn`

- src/lib.rs
This changes makes the crate no_std by default and brings in the std crate as an optional dependency. This allows the `unsync` part of the crate to be useable in no_std environments when the `std` feature is disabled.
> Allow non-std version of crate to be used in no_std environments

- src/lib.rs
- tests/test.rs
Replacing lazy_static in my codebases I've found I'm doing `Lazy::new(<_>::default)` a fair bit generally for Mutex use.
This pr streamlines that to `Lazy::default()`, in a similar way to `Arc`, `Mutex` wrappers. Although it won't work in static contexts, which sucks.
> impl Default for Lazy

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- tests/test.rs
Note that we intentionally don't add
`unsync::OnceCell::get_unchecked`:
* it doesn't do any atomic operations, so should be cheap
* given than it's cheap, there's a chance that `get_unchecked` will be
misused
* if you absolutely need it, you can `.unwrap_unchecked` on the call
site
> add sync::OnceCell::get_unchecked

- src/lib.rs
The caller not only has to make sure that the cell is initialized, but also that the data is acquired by the current thread. I can't imagine any scenario where you know it is initialized but where you didn't do an acquire yet, but it seems good to document.
> Add synchronization note to get_unchecked

- src/imp_std.rs
- tests/test.rs
Also ignore tests that don't run in Miri instead of removing them entirely; this avoids warnings.
> Miri now supports panics

- src/lib.rs
- tests/test.rs
> Implement DerefMut for Lazy

- run-miri-tests.sh
- tests/test.rs
https://github.com/rust-lang/miri/issues/940 is fixed, so we should be able to enable the leak checker now. :)
(However, we'll have to wait until https://github.com/rust-lang/rust/pull/70897 lands so that this is available via rustup.)
> miri: enable leakcheck

- src/lib.rs
I use `OnceCell` extensively in my code to cache lazily computed data on
structs. Sometimes, I mutate the data -- in which case I have to invalidate
those caches.
This is of course possible to do by oneself, but it's slightly non-obvious
that the "once" bit of OnceCell only applies in the shared reference context.
> add a `take` method which takes a mutable reference

- README.md
I noticed this problem in rust-lang/crates.io#2732 and thought it was a problem on crates.io’s side, but actually the problem is here! Here are two videos showing what the README looks like before the fix and after:
- [Before](https://streamable.com/lhizhp)
- [After](https://streamable.com/k6ygzj)
> Remove height attribute from logo in README

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- tests/it.rs
This API allows to move a T out of `Lazy<T>`.
Note that it requires an owned access to a `Lazy` -- there's no way to
reset a lazy to uninit state via `&mut Lazy<T>`, as the init function
is gone. In other words, `fn take(this: &mut Lazy<T>)` is an
impossible object.
> Add Lazy::into_value

- Cargo.toml
- src/lib.rs
- tests/it.rs
> Convert race to a default-enabled feature for targets without atomics.

- CHANGELOG.md
- src/imp_pl.rs
- src/imp_std.rs
I have observed that the program size has increased a lot after enabling the `parking_lot` feature.
`parking_lot` will actively inline methods, which leads to some unnecessary duplication of code. see https://github.com/Amanieu/parking_lot/pull/236
This PR introduces an `InlineLessRawMutex` wrapper to avoid this problem. `initialize` is a cold path, I don't think this will cause performance problems.
> Improve `imp_pl` size

- src/lib.rs
Document the allowed violation of the "once" invariant for `&mut self` methods.
Closes #153.
> Document implications of `&mut self` methods on once-ness

- CHANGELOG.md
- Cargo.toml
- src/race.rs
To make it compile on platform that have limited atomics
Fixes #155 
Note that this re-implement the Debug version of the OnceBox
because atomic-polyfill::AtomicPtr don't implement Debug (https://github.com/embassy-rs/atomic-polyfill/issues/11)
> Add an atomic-polyfill optional dependancy

- src/lib.rs
Fix a found typo when skimming through the `once_cell` documentation.
> doc: fix a typo

- CHANGELOG.md
- Cargo.toml
- src/imp_pl.rs
- src/imp_std.rs
- src/lib.rs
- tests/it.rs
This PR adds `OnceCell::with_value` to both `sync::OnceCell` and `unsync::OnceCell`. This enables creating an initialized `OnceCell` at compile time and/or without synchronization cost.
Additionally, this improve `Clone` implementations by removing a panicking branch, reducing synchronization cost and overriding `clone_from` implementation.
Closes #164
> Add `OnceCell::with_value` and improve `Clone` implementation

- src/race.rs
I believe this is the correct rationale as to why those atomic orderings were chosen in this module. This change also makes it explicit that those orderings are used in the library's public API, better allowing consumers to safely depend on it.
> Explain the atomic orderings used in race

- CHANGELOG.md
- Cargo.toml
- src/imp_pl.rs
- src/imp_std.rs
- src/lib.rs
- tests/it.rs
> add OnceCell::wait

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
closes https://github.com/matklad/once_cell/issues/102
> publish v1.12.0

- src/lib.rs
The example of `get_mut` looks like that for `new`.
Actually,  the comment before the example finishes with ':'. So, it looks like in the middle of sentence or incomplete.
> Fix comments

- .github/workflows/ci.yaml
- src/imp_std.rs
`once_cell` is an extremely widely-used crate, so it would be very nice if it conformed to the stricted/simplest/checkable model we have for aliasing in Rust. To do this, we need to avoid creating a pointer from an integer by cast or transmute. Pointers created this way can be valid, but are a nightmare for a checker like Miri. The situation is generally explained by these docs: https://doc.rust-lang.org/nightly/std/ptr/fn.from_exposed_addr.html
This implementation is mostly gross because all the APIs that would make this ergonomic are behind `#![feature(strict_provenance)]`. (in particular, it would be great to have `map_addr` here)
> Keep provenance intact by avoiding ptr-int-ptr

- xtask/Cargo.toml
- xtask/src/main.rs
- xtask/src/tidy.rs
- xtask/tests/tidy.rs
> modernize CI

- Cargo.toml
- src/imp_cs.rs
- src/imp_pl.rs
- src/imp_std.rs
- src/lib.rs
- src/race.rs
- tests/it.rs
- xtask/src/main.rs
Add implementation based on `critical-section` for embedded targets.
This started out using `critical_section::Mutex`, but tests were failing since `critical_section::with` blocks all threads during initialization, so I changed it to be basically the same as `imp_pl` without the `parking_lot` parts, since `atomic-polyfill` is based on `critical-section`.
Depends on https://github.com/rust-embedded/critical-section/pull/26.
> Add `no_std` implementation based on `critical-section`.

- CHANGELOG.md
- Cargo.toml
- src/imp_cs.rs
- src/imp_pl.rs
- src/imp_std.rs
- src/lib.rs
- src/race.rs
- tests/it.rs
- xtask/src/main.rs
This also reshuffles features a bit, to clearly separate public API from internal features.
bors r+
> publish 1.16.0-pre.1

- README.md
- src/lib.rs
I just published [generic_once_cell](https://crates.io/crates/generic_once_cell) (docs are still building).
This PR advertises generic_once_cell from the docs and the readme.
Closes https://github.com/matklad/once_cell/issues/207.
> Advertise generic_once_cell

- src/lib.rs
The given `LateInit` recipe works up until the print statement, which causes a stack overflow as the derived `Debug` implementation tries to write out:
```rs
LateInit { cell: OnceCell(A { b: LateInit { cell: OnceCell(B { a: LateInit // repeats endlessly from here
```
To fix this, I've added in a rudimentary `Debug` impl.
> Fixed `LateInit` recipe stack overflow

- CHANGELOG.md
- Cargo.toml
- src/race.rs
Like OnceBox, but stores a shared reference instead of a Box.
Mainly useful for `#![no_std]` environments where we can use it to store a `&'static T`.
> Add once_cell::race::OnceRef

- src/lib.rs
Background: I'm working on improving my unsafe Rust skills, and figuring out how `once_cell` works is one way to do that. By more elaborately explaining why `unsync::OnceCell::get(&self)` is safely implemented, I hope to help others increase their understanding of unsafe Rust as well.
(It was not obvious to me at first why `unsync::OnceCell::get(&self)` was safe. But I think I figured it out now.)
> Explain safety of `unsync::OnceCell::get(&self)` in more detail

- src/imp_std.rs
- src/lib.rs
- src/race.rs
applied select clippy lint recommendations
> Make clippy happy

- CHANGELOG.md
- Cargo.lock.msrv
- Cargo.toml
- src/lib.rs
- xtask/src/main.rs
- `DerefMut` was not delegating to `force_mut()` (contary to the by-ref APIs);
- `Lazy::force_mut` was not taking advantage of exclusive-mutability access, and instead paying shared-mutability access. Mainly, in the `sync` case, it involved atomic operations which are now skipped.
Fixes #226
> Avoid unnecessary synchronization in `{force,deref}_mut`

- src/lib.rs
- tests/it.rs
"Continuation" from https://github.com/matklad/once_cell/pull/230, which partially handles https://github.com/matklad/once_cell/issues/167.
- Incidentally, this also makes `unsync::Lazy` smaller in size in most cases, since `T` and `F` are now sharing the same `union` storage.
The `sync` can basically use the same logic (my PR paves the way for such a follow-up PR), only the whole thing would need to be moved to each of the possible `imp`lementations of `sync::OnceCell`, and special care to synchronization semantics will be in order, which I prefer to let somebody else do.
> Make `unsync::Lazy<T, F>` covariant in `F`

- src/lib.rs
- tests/it.rs
Indeed, #233 introduced a regression w.r.t `#[may_dangle]` 😔, apologies
> Revert "Make `unsync::Lazy<T, F>` covariant in `F`"

- src/imp_std.rs
The effect of having `PhantomData<*mut Waiter>` is that the `OnceCell<T>` stops being `impl<T: Send> Send for OnceCell<T>`. But we want it to be `impl<T: Send> Send for OnceCell<T>`, because we manually mark it as such.
By removing the `PhantomData` we can also remove the manual `impl Send`. The net effect is zero changes to the public API surface (including auto traits) of `once_cell`:
```
$ cargo install cargo-public-api --locked
$ cargo public-api diff origin/master..remove-unneeded-phantomdata
Removed items from the public API
=================================
(none)
Changed items in the public API
===============================
(none)
Added items to the public API
=============================
(none)
```
A variant of this PR is to remove the `PhantomData` but keep the manual `impl …
> Remove `PhantomData<*mut Waiter>` so we don't need to manually `impl Send`

- CHANGELOG.md
- Cargo.lock.msrv
- Cargo.toml
- src/imp_cs.rs
- src/race.rs
> Use `portable_atomic` instead of `atomic-polyfill`

- CHANGELOG.md
- Cargo.lock.msrv
- Cargo.toml
- src/imp_cs.rs
- src/race.rs
- xtask/src/main.rs
(updated)
- propagate `critical-section` feature selection into `portable-atomic`
- _update TEST_BETA - push RUSTFLAGS = `-A unreachable_patterns`_ - WORKAROUND ref: #261
- add `cargo test --workspace` to beginning of TEST task - resolves #262
- other minor updates
- bump minor version in Cargo.toml & update change log
CI build now fixed with TEMPORARY WORKAROUND in TEST_BETA task.
---
__ORIGINAL RATIONALE RE: propagate `critical-section` feature selection into `portable-atomic`__
Normally just using `critical-section` should be good enough for targets like super-outdated `thumbv6m-none-eabi` target. But in https://github.com/rustls/rustls/pull/2088 I would like to preserve existing use of `alloc` option, in which case I had to add explicit `portable-atomic` dependency with its …
> propagate critical-section feature selection into portable-atomic; other minor updates for v1.20.0

- Cargo.lock.msrv
- Cargo.toml
- src/race.rs
Closes #264
This implements the first of the ways I mentioned in https://github.com/matklad/once_cell/issues/264#issuecomment-2354148809.
> * New Cargo feature to use `portable-atomic`'s atomic types instead of `core`'s
(The second way mentioned there was probably more user-friendly, but I did not choose it because it would have caused `portable-atomic` to appear in Cargo.lock as a platform-specific dependency. Like cfg-specific dependencies in https://github.com/crossbeam-rs/crossbeam/pull/487#issuecomment-783365041.)
No new test case was added, because the following case is sufficient to test the situation where the `race` module is enabled (due to default features) and `portable-atomic` is used instead of `core::sync::atomic` (due to `critical-section` feature enables `portable-atomic` …
> Add portable-atomic feature and disable portable-atomic/critical-section by default

- Cargo.lock.msrv
- Cargo.toml
This removes `"portable-atomic?/require-cas"` from `race` feature to work around Cargo bug (https://github.com/rust-lang/cargo/issues/10801).
Instead, this increases the minimal version of portable-atomic to 1.8 (which includes diagnostic improvements by https://github.com/taiki-e/portable-atomic/pull/181) so that it can keep good diagnostics with compilers at least Rust 1.78 (2024-05) or later.
More context: https://github.com/matklad/once_cell/pull/265#discussion_r1783125334
This is definitely a Cargo bug, but the fix does not seem to be easy: https://github.com/rust-lang/cargo/pull/11938
In my understanding, the only users who would be affected by this workaround are users of older compilers, so I think it is acceptable.
> Remove "portable-atomic?/require-cas" from race feature

- CHANGELOG.md
- Cargo.lock.msrv
- Cargo.toml
- src/race.rs
In typical use, the Some branch is going to be taken extremely frequently but the None branch is only going to be taken once (or a very small number of times) at startup. If `get_or_try_init` is in a performance-sensitive segment of code, then it is important that `get_or_try_init` be inlined and that the compiler understands that the Some branch is (much) more likely than the None branch. When this happens, the call site basically becomes a load followed by a conditional jump that is basically never taken; which is ideal.
When `get_or_try_init` is used in many places in the user's code, it is important to avoid inlining any of the None branch into the call sites.
Unfortunately, the Rust compiler is sometimes not good at recognizing that code that calls a #[cold] function unconditionally …
> Make initialization in `OnceNonZeroUsize::get_or_try_init` `#[cold]`.

- src/race.rs
Each call to `OnceNonZeroUsize::get()` results in an atomic load as the compiler will not cache and reuse the result of an atomic load.
Provide an analogous `get_unchecked()` that uses a non-atomic load. The compiler will be able to cache and reuse the result to avoid redundant loads.
> Add `OnceNonZeroUsize::get_unchecked`.

- src/race.rs
Those seem useful, unsure if there's a reason those were not provided right away
> feat: impl `Clone for OnceBox` and `OnceBox::with_value`

- CHANGELOG.md
- Cargo.lock.msrv
- Cargo.toml
- src/race.rs
Potentially the MSRV could be reduced further as `cargo +1.63.0 check` passes, but `cargo +1.63.0 test` fails:
```
$ cargo +1.63.0 test
error: package `regex-syntax v0.8.5` cannot be built because it requires
rustc 1.65 or newer, while the currently active rustc version is 1.63.0
```
> Reduce MSRV to 1.65 by polyfilling `AtomicUsize::as_ptr()`.

- CHANGELOG.md
- Cargo.lock.msrv
- Cargo.toml
- src/race.rs
See the analogous change in
https://github.com/rust-lang/rust/pull/131746 and the discussion in
https://github.com/matklad/once_cell/issues/220.
What is the effect of this change? Not much, because before we ever execute the `compare_exchange`, we do a load with `Ordering::Acquire`; the `compare_exchange` is in the `#[cold]` path already. Thus, this just mostly clarifies our expectations.  See the non-doc comment added under the module's doc comment for the reasoning.
How does this change the code gen? Consider this analogous example:
```diff
#[no_mangle]
fn foo1(y: &mut i32) -> bool {
-    let r = X.compare_exchange(0, 1, Ordering::AcqRel, Ordering::Acquire).is_ok();
+    let r = X.compare_exchange(0, 1, Ordering::Release, Ordering::Acquire).is_ok();
r
}
```
On x86_64, there is no …
> race: Relax success ordering from `AcqRel` to `Release`.

- src/race.rs
Use `Self::get()` instead of directly loading the value, which is a DRY improvement in its own right.
Then it is trivial to split out the initialization into a `#[cold]` function, matching `OnceNonZeroUsize`.
> Mark initialization of `OnceBox::get_or_try_init` cold.

- src/race.rs
Avoid repeating type parameters and otherwise make it easier to see where a function is a constructor.
> race: Use `Self` ubiquitously.

- src/race.rs
The `current` value must always be zero and the orderings must always be `Release`/`Acquire`. Make this clearer.
> race: DRY `OnceNonZeroUsize::{init, set}` and `OnceNonZeroUsize::{get, get_or_try_init}`.

- src/race.rs
Use `Self::get()` instead of directly loading the value, which is a DRY improvement in its own right.
Then it is trivial to split out the initialization into a `#[cold]` function, matching the other implementations in the module.
This is the `OnceRef` analog of commit 90da60ba44553d893068f42155ba6778dbcf49fb.
> Mark initialization of `OnceRef::get_or_try_init` cold.

- CHANGELOG.md
- Cargo.lock.msrv
- Cargo.toml
- src/race.rs
Centralize all the pointer type casting and RMW into a new `compare_exchange` function as was done in other types in the module. Leave the dereferencing of the pointer in `init()` as `set()` doesn't ever use the old value.
> DRY `race::OnceRef::{get_or_try_init, set}`.
